package:
  name: gnina
  version: 1.1

source:
  url: https://github.com/gnina/gnina/releases/download/v1.1/gnina
  sha256: cd5f12d88f63bef2f637ef183beb24f1620ba97944d88173b76fbd373e46d84f
  fn: gnina

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('gnina', max_pin="x") }}

test:
  commands:
    - gnina --help

about:
  home: https://github.com/gnina/gnina
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: gnina (pronounced NEE-na) is a molecular docking program with integrated support for scoring and optimizing ligands using convolutional neural networks.
  description: |
    gnina is a molecular docking program that combines the empirical scoring function of AutoDock Vina
    with convolutional neural networks (CNNs) to improve binding pose prediction and virtual screening
    accuracy. It provides integrated support for scoring and optimizing ligands using these networks.
  doc_url: https://gnina.readthedocs.io/
  dev_url: https://github.com/gnina/gnina
  
extra:
  recipe-maintainers:
    - Tonylac77
